// <auto-generated />
using Honeywell.CodeExcercise.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Honeywell.CodeExcercise.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Honeywell.CodeExercise.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cat1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cat3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cat4"
                        });
                });

            modelBuilder.Entity("Honeywell.CodeExercise.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Desc1",
                            Name = "Item1",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Desc2",
                            Name = "Item2",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Desc3",
                            Name = "Item3",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Desc4",
                            Name = "Item4",
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("Honeywell.CodeExercise.Model.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "SubCat1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "SubCat2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "SubCat3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Name = "SubCat4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
